### ISSUE TITLE
avoid bots from collecting form POST URL

### ISSUE THREAD

**Issue by VincentTam** [zinefer/hugo-carbon#5]
Quoted from the linked article.

> # Bot Block for Forms
> Search engines and other robots will follow form action URLs.
>
> It turns out to be effective form spam prevention, too.

Implementation

For example, you may view the code written (originally by <span>@</span>mmistakes) for daattali/beautiful-jekyll<span>#</span>/521

:link: https://www.willmaster.com/library/manage-forms/bot-block-for-forms.php

**Comment by zinefer** [comment]
I prefer to make my forms mostly-usable without javascript so I'm not actually a fan of this type of protection.

Thanks though!
